### ISSUE TITLE
[FEATURE]  selecting another Shipping method as PostNL in Checkout. Hide the postnl-deliveryoptions

### ISSUE THREAD

**Issue by rsp-vicus** [tig-nl/postnl-magento2#152]
When selecting another Shipping method as PostNL in Checkout. Hide the postnl-deliveryoptions
![Checkout - options](https://user-images.githubusercontent.com/31655295/72976013-100dfc80-3dd2-11ea-8ca7-39dd63697b09.png)
.

It is confusing for customers

**Comment by tig-jaspersmits** [comment]
Hi @rsp-vicus ,

Thanks for contacting us and we appreciate your enhancement recommendation. I will put this on our backlog. PostNL will decide whether they want us to focus on such an improvement. I recommend keeping an eye on the release notes to see if PostNL decided to prioritize on such an enhancement. You can find the release notes here: https://docs.tig.nl/x/3YSC

Kind regards,
Jasper
TIG

**Comment by tig-support** [comment]
Note from Jen: Automatically assigned Jasper Smits to this issue as no one was assigned.

**Comment by tig-jaspersmits** [comment]
FYI: This is still on the backlog as a feature request. So far no priority has been given to this feature by PostNL. Since I can't guarantee that it will become a feature, I recommend keeping an eye on the release notes like mentioned in my previous response.

I will close this ticket.

Kind regards,
Jasper

**Comment by tig-daanvandenbergh** [comment]
@rsp-vicus, just wanted to let you know that this feature has been implemented in v1.9.1.
