### ISSUE TITLE
[FEATURE] Set Brievenbus pakje on product level

### ISSUE THREAD

**Issue by Goeny** [tig-nl/postnl-magento2#165]
The following would be a great addition to shipment handling.

Certain products are very small and there would be no problem if these would be sent in a "Brievenbus pakje".
This would safe the customer a reasonable amount of shipping costs.
i.e: A server (we sell refurbished enterprise hardware and parts) would be packed and shipped in a regular manner.
But if a customer want to order a simple SD-Card, chances are the shipping cost would be higher then the cost of the product. The customer will cancel the order and money is lost.
If the module knows this product can be sent using "brievenbus pakje" the customer pays much less for shipping and goes on ordering the product.

Idea is to set this on product level.
i.e: In the edit product page can be set this would be a "brievenbus pakje". Ignoring the regular (matrix) shipping rates.
If the ordered amount of products exceed a certain weight, the regular shipping rates apply.

**Suggestions and background**

If you have ideas for the solution write them down here. Include images, a picture is more worth than 1,000 words. If none, remove this line.

**Comment by tig-jaspersmits** [comment]
Hi @Goeny ,

Thanks for contacting us and committing this feature request. We are aware that this is a functionality that would be beneficial for the extension. It's also on our backlog, but currently on hold because there are other functionalities and improvements which have more priority.

What I would recommend is also contacting your account manager at PostNL about this. PostNL determines what improvements/features we add next to the extension.

Thanks again and it would be great if you could use our template next time you submit a feature request.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi @Goeny ,

Just heard from our development team that PostNL gave us a go to develop this feature. We will release this in an upcoming version of the PostNL extension. I recommend keeping an eye on our release notes: https://docs.tig.nl/x/3YSC

If you have any other questions, please let me know.

Kind regards,
Jasper
TIG

**Comment by Goeny** [comment]
Hi @tig-jaspersmits ,

This is excellent news.
I will keep an eye out for the upcoming releases and notes.

Thanks.

**Comment by tig-jaspersmits** [comment]
No problem!

**Comment by tig-jaspersmits** [comment]
This should be available in the new release.
I will close the ticket.

Kind regards,
Jasper
TIG
