### ISSUE TITLE
Verkeerd address_type van pickup point adres

### ISSUE THREAD

**Issue by Mark-Sherpaan** [tig-nl/postnl-magento2#17]
https://github.com/tig-nl/postnl-magento2/blob/701483ddec08058c7578f49eb1962c81bf9c9d4b/Observer/SalesOrderSaveAfter/AddressToOrder.php#L146

Hier staat het address_type van het pickup point op `shipping`. Dat lijkt me niet correct... Moet dat niet `pakjegemak` zijn? Net als bij de quotes: https://github.com/tig-nl/postnl-magento2/blob/701483ddec08058c7578f49eb1962c81bf9c9d4b/Helper/DeliveryOptions/PickupAddress.php#L133

Onze extensie haalt order informatie uit Magento en op basis van het address_type konden we (in Magento1) bepalen wat het adres van het gekozen pakje gemak punt is. Ook heb je nu in 1 order 2 adressen met het type `shipping`.

**Comment by tig-jaspersmits** [comment]
Good morning Mark,

I have created a issue on our backlog for this. You can follow the progress trough this url: https://jira.tig.nl/browse/POSTNLM2-376 PostNL will decide the priority of the issues on this backlog so it is up to them when they want us to implement it.

I recommend following that issue to stay up-to-date about the status.

Kind regards,

Jasper
TIG

**Comment by tig-rikjonkmans** [comment]
Goeiemorgen Mark,

Als het goed is heb jij al contact gehad met ons en PostNL betreft dit issue. Ik zal hieronder nog een toelichting geven over wat de mogelijkheden hiermee zijn. Dit zal ik in het engels doen zodat iedereen die het eventueel wilt gaan gebruiken kan lezen. 

The reason we can not use the 'PG_ADRESS_TYP' in the SalesOrderSave plugin is because, \Magento\Sales\Model\Order\Address\Validator::validate will trow the error;
_We can't save the address: Address type doesn't match required options_ 

We could rewrite this validator class, but that is not recommended. There for we decided to make a plugin on the getShippingAddress method of Magento. That will mean that from now $magentoOrder->getShippingAddress(), will return the PG Address (if there is an pg_address_id in the postnl order object).
