### ISSUE TITLE
[FEATURE] Just print label as batch in order screen

### ISSUE THREAD

**Issue by Daniel304** [tig-nl/postnl-magento2#190]
**Please rephrase the following line:**

As an admin I would like to see the option to bulk print just the shipping labels. The reason is two fold, namely I can print multiple shipping labels and go to the drop off point and let them scan the labels much faster. When you create a shipping label the order is immediately confirmed and i can not print the label again.

**Suggestions and background**

There currently is a dropdown in the order page please at this option there.

**Comment by Gnobama** [comment]
That would be a great option! We face the same problem, if we need for some reason print the labels again we can only do it inside the order one by one.
Because the option to reprint the label is available inside the order itself it should be possible to add this option in the grid as well. 

@Daniel304, good idea to bulk print the labels so they can be scanned from there instead of taking each parcel from the container and to put it back after the scan.

**Comment by tig-jaspersmits** [comment]
@Daniel304  and @Gnobama ,

Thanks for your input! But.. it is possible to print them again from the order grid.
You can use: PostNL - Create shipments, print labels & confirm

Since the shipment already exists and the shipment already has been confirmed, it will just print the labels.
Or am I not understanding this feature request correctly?

Looking forward to your response.

Kind regards,
Jasper
TIG

**Comment by Gnobama** [comment]
Hello Jasper,

At Sales- Shipments we have only this option PostNL - Print shipping labels & confirm shipment
At Sales- Orders we do have the option you mentioned (PostNL - Create shipments, print labels & confirm) but we get an error if we want to reprint the labels.
[POSTNL-0252] - There are no valid labels generated. Please check the logs for more information
Can not process order 000009578, because it is not new or in processing

**Comment by tig-jaspersmits** [comment]
@Gnobama ,

That's strange. I can just keep downloading the labels like that without receiving an error.
It might be better to send us an e-mail on sd@tig.nl. We can take a look at your environment if you want.

Kind regards,
Jasper
TIG

**Comment by Daniel304** [comment]
this was due to an issue with another extension. sorry for this
