### ISSUE TITLE
[BUG] Api\Data\ShipmentInterface breaks WSDL generation

### ISSUE THREAD

**Issue by ainigma32** [tig-nl/postnl-magento2#194]
After upgrading to version 1.9.4 the system no longer shows the WSDL for any SOAP webservice.

**To Reproduce**
1. Go to https://example.com/soap/all?wsdl=1&services=catalogProductRepositoryV1

**Expected result**
Rendering of the WSDL

**Actual result**
A web-api error report

**Workaround**
Add full namespace to docblock of function definition for getPostNLOrder()

``` 
@return \TIG\PostNL\Api\Data\OrderInterface
```

instead of

```
@return Order
```

- Magento version:  2.3.3
- PHP version: 7.2
- TIG PostNL version: 1.9.4

**Comment by SolsWebdesign** [comment]
Please fix this as this is a major issue for Magento SOAP users.

**Comment by tig-dennisvanderhammen** [comment]
Hi @ainigma32 and @SolsWebdesign ,

Thank you both for letting us know, providing us a solution and providing us a way to reproduce it. We appreciate that.
For people stumbling upon this, @ainigma32 is talking about the file Api/Data/ShipmentInterface.php

A workaround for this problem is replacing line 370 with:
     * @return \TIG\PostNL\Api\Data\OrderInterface

After this, please flush the config_webservice cache:
bin/magento c:f config_webservice

As for the issue itself, I'll push these changes to our private repository. You can expect it in the next release!

**Comment by tig-dennisvanderhammen** [comment]
Hi @ainigma32 and @SolsWebdesign,
We just released version v1.9.4.1 which fixes this issue. Thank you again for pointing this out!
