### ISSUE TITLE
[FEATURE] Auto select first delivery option day

### ISSUE THREAD

**Issue by JoostWan** [tig-nl/postnl-magento2#202]
Auto select first delivery option day when the PostNL options are loaded. So the customer don't need to select the first day. 

![Screenshot 2020-09-03 at 15 40 24](https://user-images.githubusercontent.com/5435412/92122507-cec7db80-edfb-11ea-8565-6ba927c43528.png)

**Comment by tig-jaspersmits** [comment]
Hi @JoostWan ,

Thanks for your feature request. I'll add it to our backlog.
It's up too PostNL if they want to add this feature.

Kind regards,
Jasper

**Comment by fourtwenty** [comment]
I support this suggestion

**Comment by tbaltissen** [comment]
@tig-jaspersmits do you have any update on this? Thanks!

**Comment by tig-jaspersmits** [comment]
Hi @tbaltissen ,

Currently this is still on the backlog as a feature request. So no ETA for this one yet. I'll ask our developers if we are going to do something with it. I do think we want to. Let me get back to you when I have more info.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi @tbaltissen ,

Pull request for this is currently open. Expect this is one of the upcoming new releases of the extension.

Kind regards,
Jasper
TIG

**Comment by tbaltissen** [comment]
@tig-jaspersmits  Thanks for your update! We will try it out very soon.

**Comment by tig-jaspersmits** [comment]
@tbaltissen , no problem! You can keep an eye on the release notes here: https://docs.tig.nl/x/3YSC

Kind regards,
Jasper
TIG

**Comment by tbaltissen** [comment]
@tig-jaspersmits any idea if we can expect a new release soon? Thanks!

**Comment by tig-jaspersmits** [comment]
Hi @tbaltissen ,

No information yet. PostNL isn't a big fan of bring out a new version before the holidays.
If you want I can try to share the modifications of that pull request with you. But you would need to implement and extensively test it yourself. Let me know if that would help you out.

Kind regards,
Jasper
TIG

**Comment by tbaltissen** [comment]
@tig-jaspersmits Yes please share it so we can try it out. Our client does really want it before the holidays as it'll be a checkout flow improvement. Thanks!

**Comment by tig-jaspersmits** [comment]
@tbaltissen just noticed they are still working on it. So I don't have any guarantee this is working 100% since it's not in a ready to release state yet. Therefor I'll mention it again, please test this a lot and make sure you are currently using the latest version of the extension.

This file: view/frontend/web/js/Renderer/DeliveryOptions/Delivery.js 

Add this on row 181: 
`this.selectFirstDeliveryOption();`

Add this on row 191: 
`this.selectFirstDeliveryOption();`

Add this on row 202: 
`this.selectFirstDeliveryOption();`

On row 251 replace this: 
`})`

With:

[        }),

        selectFirstDeliveryOption: function () {
            var deliveryDays = this.deliverydays();
            if (deliveryDays !== undefined && deliveryDays[0] !== undefined && deliveryDays[0][0] !== undefined) {
                this.selectedOption(deliveryDays[0][0]);
                this.saveSelectedOption(this.selectedOption());
            }
        }](url)

As reference I've added a screenshot so it's clear where to place it.

<img width="1635" alt="Screenshot 2020-11-17 at 12 26 01" src="https://user-images.githubusercontent.com/25201501/99384707-1bd22e80-28d0-11eb-80e5-a211ed33d8de.png">

Kind regards,
Jasper
TIG

**Comment by tig-jeffreybranderhorst** [comment]
Hi @JoostWan and @tbaltissen ,

If you update to the newest version of PostNL the first option should be auto selected. Thank you for your patience if after updating you still have questions for us don't hesitate to contact us at support@tig.nl.

Have a great day,
Jeffrey
