### ISSUE TITLE
[BUG] Trying to install on 2.3.4-p2 -- out of memory on setup:upgrade 

### ISSUE THREAD

**Issue by janssensjelle** [tig-nl/postnl-magento2#206]
We are unable to install the PostNL extension on Magento 2.3.4-p2. We are using PHP 7.2. Adding it via composer goes fine. When doing bin/magento setup:upgrade the memory usage goes up to the max and is then killed. After trying we also tried installing the bpost extension and others, which install fine. Please advice. 

**To Reproduce**
1. Load extension via composer
2. bin/magento setup:upgrade

**Expected result**
The extension is installed.

**Actual result**
The extension is not installed. The process of setup:upgrade gets killed due to having no more memory. The virtual box we use has 8 gb of ram and all is being used during the install of this extension.

**Workaround**
None

**Screenshots**
https://imgur.com/a/roZI60m

- Magento version: 2.3.4-p2
- PHP version: 7.2.33
- TIG PostNL version: 1.9.4.1, tried other older versions too. Same result.

**Comment by tig-jaspersmits** [comment]
Hi @janssensjelle ,

Thanks for your message. I've just tried reproducing this, but I'm not running into OOM errors.
I would think this is related to your server settings. I've asked a colleague about this and will follow up on this issue.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi @janssensjelle ,

Just discussed this with our team and we are able to run magento setup:upgrade without any problems using 4gb's of memory. We don't think this is related to the extension since we are unable to reproduce it and haven't encountered similar issues recently or in the past.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
@janssensjelle ,

When you run **php -i | grep "memory_limit"** , what do you see? It could be that your web/browser uses 8gb but that cli is configured for 256mb for example. More information on checking the memory limit can be found here: https://stackoverflow.com/questions/10208698/checking-memory-limit-in-php/10209530

Kind regards,
Jasper
TIG

**Comment by janssensjelle** [comment]
@tig-jaspersmits , 

The CLI is configured to use unlimited memory. The only extension I had issues with installing seems to be this one.  

php -i | grep "memory_limit"
144:memory_limit => -1 => -1

PHP 7.2.33-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Aug  7 2020 14:43:59) ( NTS )

**Comment by tig-jeffreybranderhorst** [comment]
Hi, 
sorry to hear that, at this moment I am confident that it still looks like something in your local environment. To be sure, you have tested it in Magento 2.3.4-p2, not the latest Magento 2.3.5-p2, right?
Could you please try to run these commands:
$ php -d memory_limit=2G /path/to/composer require tig/postnl-magento2
$ php -d memory_limit=2G bin/magento setup:upgrade

This should give no errors, does this solve the issue?

Kind regards,
Jeffrey
TIG

**Comment by janssensjelle** [comment]
Hi Jeffrey

Thanks for the commands. Yes, 2.3.4-p2. Some of the extension we use are not compatible yet with 2.3.5-p2. 

I have tried the commands as you said, same result. The memory consumption of the vagrant box go up to 8gb and then it is killed.

> 
> $ php -d memory_limit=2G bin/magento setup:upgrade
> Cache cleared successfully
> File system cleanup:
> /var/www/adcvetshop/generated/code/Adc
> /var/www/adcvetshop/generated/code/Aheadworks
> /var/www/adcvetshop/generated/code/Akeneo
> /var/www/adcvetshop/generated/code/Composer
> /var/www/adcvetshop/generated/code/Dotdigitalgroup
> /var/www/adcvetshop/generated/code/MSP
> /var/www/adcvetshop/generated/code/MageSuite
> /var/www/adcvetshop/generated/code/Magento
> /var/www/adcvetshop/generated/code/Meetanshi
> /var/www/adcvetshop/generated/code/Smile
> /var/www/adcvetshop/generated/code/Symfony
> /var/www/adcvetshop/generated/code/Wyomind
> /var/www/adcvetshop/generated/code/Yotpo
> /var/www/adcvetshop/generated/code/Zend
> The directory '/var/www/adcvetshop/generated/metadata/' doesn't exist - skipping cleanup
> /var/www/adcvetshop/pub/static/adminhtml
> /var/www/adcvetshop/pub/static/deployed_version.txt
> /var/www/adcvetshop/pub/static/frontend
> /var/www/adcvetshop/var/view_preprocessed/pub
> Updating modules:
>

**Comment by tig-dennisvanderhammen** [comment]
Hi @janssensjelle,

I've looked into the memory usage of the scripts, and it seems that with the PostNL extension installed the total memory usage of my setup:upgrade command is about 138MB. This is from an environment with multiple extensions installed, where PostNL previously hasn't been installed yet.

Looking at the output of your command line it seems that the issue is probably in one of the things specified at the bottom of my message. Can you please try setting some debug points around the upgrade command (specifically at the end of the updateModulesSequence() function and the start of the installSchema() function in the execute command)? \Magento\Setup\Console\Command\UpgradeCommand::execute

1. Reading the app/etc/config.php (\Magento\Setup\Model\Installer::createModulesConfig, called on line 1217, straight after the "Updating modules:" line)
2. Checking the database connection, which happens in the same file on: setup/src/Magento/Setup/Model/Installer.php:1432
3. Getting the database prefix (seems unlikely)
4. Your MySQL (or other database system) disconnects when Magento executes one of the following queries:
![image](https://user-images.githubusercontent.com/23072926/94661529-76570180-0307-11eb-81d4-441dbc896af3.png)
![image](https://user-images.githubusercontent.com/23072926/94661859-e4032d80-0307-11eb-95ba-993c8b7c9d31.png)
5. Reading the setup_module, session, cache, cache_tag or flag table (unlikely, I think it's save to assume these tables already exists. This is skipped when it already exists)

Kind regards,
Dennis van der Hammen

**Comment by janssensjelle** [comment]
Hi guys

I was able to pinpoint the culprit by selectively disabling extensions. It seems that https://github.com/magesuite/cache and https://github.com/magesuite/frontend are causing the issue. This integrates automatically with the Magesuite theme: https://magesuite.io/

Disabling this extension allows for the install to succeed.

**Comment by janssensjelle** [comment]
@tig-dennisvanderhammen ,

Thank you. Via selective disabling some extensions, I have come to the conclusion that the cause lies with an incompatibility with https://github.com/magesuite/frontend and https://github.com/magesuite/cache. Could you perhaps shed a light as to why these are not colliding with the PostNL extension? This is the only extension that has trouble installing.

Thanks!

**Comment by tig-dennisvanderhammen** [comment]
Hi @janssensjelle,

Thank you for sharing this information.
Could it be that your virtual box allows a higher stacktrace than 256?

It seems that once you activate the MageSuite Cache extension, an infinite loop occurs in the following class and method.
\TIG\PostNL\Service\Framework\ValidationState::isValidationRequired

It seems that your environment simply runs out of memory before such an error is shown in your environment.
Anyway, it seems that this method was added for Magento 2.1 developer mode compatibility purposes. Since we have dropped Magento 2.1 support long ago, I personally wouldn't hesitate in throwing this preference out (<preference for="\Magento\Framework\App\Arguments\ValidationState" type="TIG\PostNL\Service\Framework\ValidationState"/>).

I'll create an internal pull request for this, but a solution for you might be disabling line 46 in TIG/PostNL/etc/di.xml and flushing your cache.

Thank you again for sharing this with us!

**Comment by janssensjelle** [comment]
Hey @tig-dennisvanderhammen ,

Thank you. That seems to work!

**Comment by tig-dennisvanderhammen** [comment]
@janssensjelle,
We have included the changes that I mentioned in my previous comment in the latest version that just got released (version v1.9.5). Thank you again for helping us reach this solution!

**Comment by tig-dennisvanderhammen** [comment]
Ahh @janssensjelle,

I looked over your last message. I would recommend getting in touch with the support of PostNL to fix that issue, as Matrix rates seem to work on a core environment.

To reach out to them please send a mail to digitaleklantsupport@postnl.nl and explain your issue to them.
