### ISSUE TITLE
Uncaught Error: Call to a member function getProductCode() on null

### ISSUE THREAD

**Issue by SilvanLaroo** [tig-nl/postnl-magento2#22]
Steps to reproduce
--
1. Install version v1.1.4
2. Finish order as normal user

Expected result
--
1. Be able to create shipmentlabel from admin (from order page in admin)

Actual result
--
1. From order page I select 'Ship'
2. I see this page: https://www.dropbox.com/s/58urzp72ecs0uxl/Schermafbeelding%202017-10-06%20om%2015.31.07.png?dl=0
3. In the Nginx logs I see this error: https://www.dropbox.com/s/pbjlzev0aboi8kw/Schermafbeelding%202017-10-06%20om%2015.32.43.png?dl=0
4. If I check the table tig_postnl_order, there is no entity created for this order

**Comment by tig-jaspersmits** [comment]
Hi Silvan,

I tried to reproduce this, but i am able to choose shipping options on this page. See my attached image as reference. 

![shipping-options](https://user-images.githubusercontent.com/25201501/31534999-867389da-aff9-11e7-8008-507a1ab91376.png)

What i recommend is that you contact PostNL about this so they can try and help you further. If they are unable to provide you a solution they will let us know and we will contact you to investigate this.

Kind regards,

Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi Silvan,

I just discussed this with my colleague and he said that this might be caused due to a conflict with Multisafepay. Are you by any chance using their extension?

Kind regards,

Jasper
TIG

**Comment by SilvanLaroo** [comment]
Hi Jasper,

Yes, we are using Multisafepay. We're in contact with them, they will provide a fix for the problem in their extension. If this issue still persists after this fix I'll let you know.

**Comment by tig-jaspersmits** [comment]
Hi Silvan,

Thanks for letting us know. For as far as i know we are also in contact with them to get this fixed so we can solve it in a future update.

Kind regards,

Jasper
TIG

**Comment by SilvanLaroo** [comment]
Hi Jasper,

We had this issue again today. The error is thrown because there is no record in the tig_postnl_order table for the order. This is not the same as the problem with MultiSafepay.

**Comment by tig-jaspersmits** [comment]
Hi Silvan,

Could you try installing the latest version of the extension? We recently updated to version 1.1.6 We fixed the issue from our side concerning Multisafepay. We also had contact with them and the remaining issue seems to be caused by the Multisafepay platform.

I highly recommend contacting them after you installed version 1.1.6. Because after quite some extensive research we concluded that the problem you are experiencing is related to the Multisafepay platform.

If you want more information about this it might be better to give us a call.

Kind regards,

Jasper
TIG
