### ISSUE TITLE
shipmentProductOption and shipmentoption of POstNl are not store in order

### ISSUE THREAD

**Issue by Cornoud** [tig-nl/postnl-magento2#24]
In order to link POST shipment to POSTNL WMS module it would be nice to have
shippingAgentCode (eg 03085) stored in the order as well as storing the shipmentproductOption (eg 118) and ShipmentOption (eg 007)

**Comment by tig-jeffreybranderhorst** [comment]
Goodmorning Cornoud,

First of all, thank you for contacting us with this improvement for our extension.

I have talked to one of our programmers about this and he said it was a good idea, so because of that, I have created an issue on our backlog to add this to the extension. You can find it here:
https://jira.tig.nl/browse/POSTNLM2-388

He also noted that the product code (3085) and the shipment type (Evening) are already stored in the `tig_postnl_order` table.

In consultation with PostNL we are gonna decide if and when we are gonna add this to the extension.

Sincerely,
Jeffrey Branderhorst

**Comment by tig-rikjonkmans** [comment]
Goodmorning Cornoud, 

With the new release (1.3.1) these values are stored on order and shipment table. 

The codes you refer to are as followed. 
shippingAgentCode -> product_code -> getProductCode()
shipmentproductOption -> ac_characteristic -> getAcCharacteristic()
ShipmentOption -> ac_option -> getAcOption()
