### ISSUE TITLE
We get multiple errors per day in our Exception logs and error reporting.

### ISSUE THREAD

**Issue by jwbos-uhg** [tig-nl/postnl-magento2#246]
We get multiple errors per day in our Exception logs and error reporting.

**To Reproduce**

**Expected result**
No Errors

**Actual result**
We got errors and we don't know if an actual order is done or not

**Workaround**
None

**Screenshots**
**main.CRITICAL: Warning: Illegal string offset 'Name' in /var/www/html/website.com/vendor/tig/postnl-magento2/Helper/DeliveryOptions/OrderParams.php on line 267 {"report_id":"69698eb557563b8a83377faf5b6bcf572f8c8c6daa90be2dd1205f1787a2174d","exception":"[object] (Exception(code: 0): Warning: Illegal string offset 'Name' in /var/www/html/website.com/vendor/tig/postnl-magento2/Helper/DeliveryOptions/OrderParams.php on line 267 at /var/www/html/website.com/vendor/magento/framework/App/ErrorHandler.php:61)"} []**

** Please complete the following information**
- Magento version: [e.g. Magento 2.3.6]
- PHP version: [e.g. 7.2.0]
- TIG PostNL version: [e.g. 1.9.7]

**Comment by tig-jeffreybranderhorst** [comment]
Hi @jwbos-uhg,

Your error appears when a customer selects a delivery option or pickup location.
When the customer selects one, the extension starts am ajax call to save the selected option. The params will contain an address, as shown on the following screenshot.

![image](https://user-images.githubusercontent.com/23314965/113268988-4ac5cb80-92d8-11eb-8125-05e563d4ed1e.png)

In your case, it seems that the params aren't being sent properly, which could be caused by a third party plugin, as we are unable to reproduce this error on a core environment with the Luma theme.

Have a great day,
Jeffrey
