### ISSUE TITLE
Is module version 1.9.7 compatible with magento 2.3.2?

### ISSUE THREAD

**Issue by jdereus87** [tig-nl/postnl-magento2#247]
**Question**
A client wants to try the tig-nl postnl module. I downloaded the module via composer, but when running bin/magento a class seems to be missing:
Zend\ServiceManager\AbstractPluginManager

It seems the servicemanager from Zend gets deleted when I install the tig package. The package is still required in the Zend/MVC package so it gives an error.

Should I get an older version? Or is the module simply not compatible with 2.3.2?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @jdereus87,

PostNL version 1.9.4.1 or lower uses Zend instead of Laminas, the newest versions of the PostNL extension do not use Zend/Barcode anymore. You can still install the older PostNL extension by adding a version to the require. Example: composer require tig/postnl-magento2:v1.9.4.1

If 1.9.4.1 still is giving you problems I would like to ask you to contact us at support@tig.nl so we can help you further.

Have a great day,
Jeffrey
