### ISSUE TITLE
Feature request: compatibility with Magestore Onestepcheckout

### ISSUE THREAD

**Issue by Tjitse-E** [tig-nl/postnl-magento2#26]
Hi,

We're using the Magestore Onestepcheckout, in combination with Magento 2.2 and PostNL v1.1.5-alpha. Only the PostNL shipping method is visible in the checkout, but the delivery options aren't rendered.  Are there any plans to include support for third party checkout modules in one of the next releases?

Checkout screen:
![afrekenen](https://user-images.githubusercontent.com/14849044/31820229-aca59330-b5a0-11e7-90b9-febd2378f2cf.png)

**Comment by tig-jeffreybranderhorst** [comment]
Hi Tjitse,

Thank you for contacting us. The delivery options will only show when the address information is filled, did you already try it with an address?
If you already tried this i will put it on our backlog. But there are already plans to implement support for 3rd party checkout extensions in the future.

**Comment by Tjitse-E** [comment]
Hi Jeffrey,

Good point, I've checked this again with the address information filled but this didn't make a difference.

**Comment by tig-jeffreybranderhorst** [comment]
Hi Tjitse,

First of all, I'm sorry that I didn't see your response instantly. If the delivery options still ain't working it is probably because the two extensions aren't compatible with each other. 

I just created an issue about making the PostNL extension compatible. with the most used One step checkout. You can follow this issue here: https://jira.tig.nl/browse/POSTNLM2-405

**Comment by tig-jeffreypeeters** [comment]
Hey Tjitse,

It seems that One Step Checkout is no longer provided by the Magestore so we've decided to remove the issue from our backlog. We will be closing this issue but if you've any further questions feel free to contact us at [sd@tig.nl](mailto:sd@tig.nl).

King regards,

Jeffrey Peeters
TIG
