### ISSUE TITLE
[BUG] Orders not fulfilling due to error

### ISSUE THREAD

**Issue by Daniel304** [tig-nl/postnl-magento2#275]
I have updated tig/postnl from version 1.9.9 to 1.10.0 yesterday
We are running magento 2.3.4-p1 on php7.4
Since the upgrade orders are not saving through our checkout and our POS system,, The error we are getting in the error log is:

system.log
`[2021-10-18 17:07:08] main.CRITICAL: Saving order 000017399 failed: Notice: Array to string conversion in /export/www/www.bricktaifever.nl/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3170 [] []`
exception.log
`[2021-10-18 18:12:06] main.CRITICAL: Notice: Array to string conversion in /export/www/www.brickfever.nl/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3170 {"exception":"[object] (Exception(code: 0): Notice: Array to string conversion in /export/www/www.brickfever.nl/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3170 at /export/www/www.brickfever.nl/vendor/magento/framework/App/ErrorHandler.php:61)"} []`

Reverting back to 1.9.9 did unfortunately not do the trick

**Comment by albundy2** [comment]
I see two different domain addresses in the error log: www.bricktaifever.n<http://www.bricktaifever.nl>l which not exist and www.brickfever.nl<http://www.brickfever.nl> which exist. May first solve this and then test again
Regards Marcel
Brickfever LEGO Specialist Nederland<http://www.brickfever.nl/>
BrickFever LEGO Specialist Technic Starwars Minifigs Ninjago City Creator Specials Exclusives Expert
www.brickfever.nl


________________________________
Van: daniel van den Oord ***@***.***>
Verzonden: maandag 18 oktober 2021 20:14
Aan: tig-nl/postnl-magento2 ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [tig-nl/postnl-magento2] [BUG] Orders not fulfilling due to error (Issue #275)


I have updated tig/postnl from version 1.9.9 to 1.10.0 yesterday
We are running magento 2.3.4-p1 on php7.4
Since the upgrade orders are not saving through our checkout and our POS system,, The error we are getting in the error log is:

system.log
[2021-10-18 17:07:08] main.CRITICAL: Saving order 000017399 failed: Notice: Array to string conversion in /export/www/www.bricktaifever.nl/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3170 [] []
exception.log
[2021-10-18 18:12:06] main.CRITICAL: Notice: Array to string conversion in /export/www/www.brickfever.nl/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3170 {"exception":"[object] (Exception(code: 0): Notice: Array to string conversion in /export/www/www.brickfever.nl/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3170 at /export/www/www.brickfever.nl/vendor/magento/framework/App/ErrorHandler.php:61)"} []

Reverting back to 1.9.9 did unfortunately not do the trick

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftig-nl%2Fpostnl-magento2%2Fissues%2F275&data=04%7C01%7C%7C4752cda990b24e41220208d992632aa8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637701776884552336%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lwoDvfVCJH8VfLHqcDQ5xkfrOocQdsadSH%2BYq8KNFGU%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADYXDFISZH6UZ2ANCKVLC6DUHRPZLANCNFSM5GHINOYQ&data=04%7C01%7C%7C4752cda990b24e41220208d992632aa8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637701776884562332%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jbfgpE3r6qibJrJvbtzobAB1ELL3%2BNa%2FdLwERkXq0Fw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C4752cda990b24e41220208d992632aa8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637701776884562332%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QB9MbxpGjwH%2B8IZnaMEKNS82bJHk0Bx5HDxLwgURssw%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C4752cda990b24e41220208d992632aa8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637701776884572324%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dn%2FIONATQIbN0QH8lwv9pPwb9F8mmQhl6xvTKa66vEg%3D&reserved=0>.

**Comment by Daniel304** [comment]
This was a copy paste error on my side the only domain is www.brickfever.nl

**Comment by Daniel304** [comment]
we are using mageplaza one step chekout: disabling this checkout throws the full error to the browser:
`1 exception(s):
Exception #0 (Exception): Notice: Trying to access array offset on value of type null in /export/www/stage24.brickfever.nl/vendor/tig/postnl-magento2/Plugin/Postcodecheck/LayoutProcessor.php on line 205

Exception #0 (Exception): Notice: Trying to access array offset on value of type null in /export/www/stage24.brickfever.nl/vendor/tig/postnl-magento2/Plugin/Postcodecheck/LayoutProcessor.php on line 205
<pre>#1 TIG\PostNL\Plugin\Postcodecheck\LayoutProcessor->processAddress() called at [vendor/tig/postnl-magento2/Plugin/Postcodecheck/Mageplaza/LayoutProcessor.php:78]
#2 TIG\PostNL\Plugin\Postcodecheck\Mageplaza\LayoutProcessor->processMageplazaBillingFields() called at [vendor/tig/postnl-magento2/Plugin/Postcodecheck/Mageplaza/LayoutProcessor.php:63]
#3 TIG\PostNL\Plugin\Postcodecheck\Mageplaza\LayoutProcessor->afterProcess() called at [vendor/magento/framework/Interception/Interceptor.php:146]
#4 Mageplaza\Osc\Block\Checkout\LayoutProcessor\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#5 Mageplaza\Osc\Block\Checkout\LayoutProcessor\Interceptor->___callPlugins() called at [generated/code/Mageplaza/Osc/Block/Checkout/LayoutProcessor/Interceptor.php:23]
#6 Mageplaza\Osc\Block\Checkout\LayoutProcessor\Interceptor->process() called at [vendor/magento/module-checkout/Block/Onepage.php:81]
#7 Magento\Checkout\Block\Onepage->getJsLayout() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#8 Magento\Checkout\Block\Onepage\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#9 Magento\Checkout\Block\Onepage\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#10 Magento\Checkout\Block\Onepage\Interceptor->___callPlugins() called at [generated/code/Magento/Checkout/Block/Onepage/Interceptor.php:23]
#11 Magento\Checkout\Block\Onepage\Interceptor->getJsLayout() called at [vendor/magento/module-checkout/view/frontend/templates/onepage.phtml:23]
#12 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
#13 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/View/Element/Template.php:273]
#14 Magento\Framework\View\Element\Template->fetchView() called at [vendor/magento/framework/View/Element/Template.php:303]
#15 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1114]
#16 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1118]
#17 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:678]
#18 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:578]
#19 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:555]
#20 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#21 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#22 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#23 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#24 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#25 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#26 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#27 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#28 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#29 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#30 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#31 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#32 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#33 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#34 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#35 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#36 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#37 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#38 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#39 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:975]
#40 Magento\Framework\View\Layout->getOutput() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#41 Magento\Framework\View\Layout\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#42 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#43 Magento\Framework\View\Layout\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:41]
#44 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:260]
#45 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#46 Magento\Framework\View\Result\Layout->renderResult() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#47 Magento\Framework\View\Result\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#48 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/Magezon/Builder/Plugin/View/Result/Layout.php:24]
#49 Magezon\Builder\Plugin\View\Result\Layout->aroundRenderResult() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#50 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/Magezon/Core/Plugin/View/Result/Layout.php:24]
#51 Magezon\Core\Plugin\View\Result\Layout->aroundRenderResult() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#52 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#53 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:23]
#54 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#55 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#56 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
</pre>`

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Daniel304 ,

We tested PostNL on 2.4.3-p1 with different kind of products and all orders were successful. This is on a default Magento checkout. You say you turned off your OSC and this is still happening also after reverting PostNL. Did you turn off the OSC via the backend or did you do this on command line? This could be caused by using PostNL and Mageplaza as a combination. What version of Mageplaza are you using? And maybe you could also already contact  digitaleklantsupport@postnl.nl, so PostNL can also take a look at this, so they know there are issues. I will also try to reproduce it again but with the OSC and contact PostNL from our side to ask for support on the OSC. 

Have a great day,
Jeffrey

**Comment by Daniel304** [comment]
workaround by editing /vendor/magento/framework/DB/Adapter/Pdo/Mysql.php line 3170
                if(!is_array($value)) $value  = (string)$value;
                else $value = '';
                // error_log(json_encode($value),0);
                $value  = (string)$value;
                if ($column['NULLABLE'] && $value == '') {
                    $value = null;
                }
                break;

**Comment by tig-jeffreybranderhorst** [comment]
Hey @Daniel304 ,

Thank you for the workaround, do I understand correctly, you got it working now? 

Have a great day,
Jeffrey
