### ISSUE TITLE
[QUESTION] Enable Globalpack

### ISSUE THREAD

**Issue by memen45** [tig-nl/postnl-magento2#294]
What settings are required to use Globalpack shipping option?

In PostNL business account, there is a 'Globalpack customer code' and 'Barcode serie Gloablpack', however, in Magento extension there is 'Barcode type' and 'Barcode Range'
![afbeelding](https://user-images.githubusercontent.com/27782135/157869846-d662e831-80c2-4c2f-9b29-b8ca10886a5d.png)

Creating the label for a globalpack package is currently failing, but the logs are empty. Should the PostNL 'Globalpack customer code' be split in Type and Range?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @memen45,

Is the 'Global pack customer code' 2 letters? Because then this should be your barcode type and the range should contain 4 digits.  If this is not the case, I suggest you contact PostNL for further support on this issue, they can tell you where to find the correct information. You can contact them via digitaleklantsupport@postnl.nl 

Have a great day,
Jeffrey

**Comment by memen45** [comment]
The customer code contains letters and digits. Splitting was indeed the solution. Thanks for your response!
