### ISSUE TITLE
[BUG] admin section empty - error in apiCredentials.phtml

### ISSUE THREAD

**Issue by abvdveen** [tig-nl/postnl-magento2#301]
After updating to Magento 2.3.7-p3 and PostNL 1.12.0 the admin section is empty, due to this error in system.log:

main.CRITICAL: Notice: Undefined variable: escaper in /data/web/magento2/vendor/tig/postnl-magento2/view/adminhtml/templates/config/validate/apiCredentials.phtml on line 49 [] []

Magento: 2.3.7-p3
PostNL: 1.12.0
PHP 7.3.31

**Comment by tig-jeffreybranderhorst** [comment]
Hi @abvdveen,

Thank you for contacting us, we are going to test this. We have not released a version yet that supports the newest Magento's versions because we need to test it before releasing the new version.
Thank you again for already submitting this, I will place it on the backlog, so we can fix this for the new release.

Have a great day,
Jeffrey

**Comment by tig-vincentthart** [comment]
Hi @abvdveen 

We just released a new version v1.12.2 with support for the latest versions of Magento.

Have a nice day!
Vincent
