### ISSUE TITLE
[BUG] Compatibility issue with DHL Shipping

### ISSUE THREAD

**Issue by vacla** [tig-nl/postnl-magento2#318]
**To Reproduce**
1. run bin/magento cron:run
Since normally shipment async grid insert doesn't run `$this->notSyncedDataProvider->getIds($this->mainTableName, $this->gridTableName)` normally.

**Expected result**
No Errors in exception

**Actual result**
[2022-06-30 09:38:05] report.ERROR: Unable to determine order IDs for grid update. {"exception":"[object] (Zend_Db_Statement_Exception(code: 42): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'order_grid.nrshipping_label_status' in 'where clause', query was: SELECT `label_status`.`order_id` FROM `nrshipping_label_status` AS `label_status`
 INNER JOIN `sales_shipment_grid` AS `order_grid` ON label_status.order_id = order_grid.entity_id WHERE (order_grid.nrshipping_label_status != label_status.status_code) OR (order_grid.nrshipping_label_status IS NULL) at /app/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'order_grid.nrshipping_label_status' in 'where clause' at /app/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} []

**Workaround**
Disable the `TIG_PostNL_ShipmentPlace` plugin.

**Screenshots**

** Please complete the following information**
- Magento version: 2.4.3
- PHP version: 7.4
- TIG PostNL version: 1.12.2
- dhl/shipping-m2: 2.5.0

**Comment by tig-jeffreybranderhorst** [comment]
Hi @vacla ,

We have tested this on a clean environment,  but were not able to reproduce it. Then I saw DHL is only at version 1.0.37.  It looks like you are using the extension of netresearch. Because PostNL does not always offer compatibility with third party extension, I suggest you contact PostNL at digitaleklantsupport@postnl.nl to tell them you are wishing a compatibility for this extension.   If you got more questions, let us know. 

Have a great day,
Jeffrey
