### ISSUE TITLE
Calculate shipping fee after discount

### ISSUE THREAD

**Issue by ThomasMW** [tig-nl/postnl-magento2#345]
We use the Matrix rate to calculate shipping fees at the checkout. At this point the shipping fee is based on the subtotal before any discount is applied. We would like for the shipping fee to be based on the subtotal **after** any discount is applied.

Is there a way to apply this using the extension?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @ThomasMW ,

Together with PostNL we decided to calculate this shipment cost like this. We made it so that if a customer reaches free shipment barely that they won't have to pay shipment cost after using a coupon.  There is no option to switch this, if you want it to be an option in the future then I suggest you contact PostNL for this. 
You can contact them directly via digitaleklantsupport@postnl.nl 

Have a great day,
Jeffrey
