### ISSUE TITLE
Post office locations not showing

### ISSUE THREAD

**Issue by tombeachell** [tig-nl/postnl-magento2#36]
I've connected the module with my api details, and the post office locations aren't showing when you select post nl, there are no errors when I run any commands and my console is clean?

**Comment by tig-jaspersmits** [comment]
Hi Tom,

Could it be that my colleague Jeffrey already helped you with this?
If not, i would recommend contacting PostNL about this. Because we need to investigate this within your Magento environment.

You can send them an e-mail on citservicedesk@postnl.nl or call with them on 088-2255652. If they don't have a solution available they will inform us to investigate this further.

–
Met vriendelijke groet / Kind regards / Mit freundlichen Grüßen / 最好的祝福,
Jasper Smits
CUSTOMER CARE SPECIALIST
020 - 21 81 000
