### ISSUE TITLE
Order update causes MySQL error when quote is missing

### ISSUE THREAD

**Issue by VesnaS** [tig-nl/postnl-magento2#37]
Description
--
By default, Magento deletes quotes that are expired (converted to orders) after some period of time. It uses cron job, and the class is vendor/magento/module-sales/Cron/CleanexpiredQuotes, execute() method.
Because of this, Magento doesn't have foreign key in the "sales_order" table for the "quote_id" column. 

Your extension creates "tig_postnl_order" table, with the "quote_id" column, and the FK constraint to the "quote" table. It also has "sales_order_save_after" event observer "tig_postnl_sales_order_place_after", which updates extension's table.

We have a problem when third-party service tries to update valid order, that has "quote_id" of the already removed quote. Your observer tries to load postnlOrder by "quote_id", but it can't find it because of the "On Delete SET NULL" FK option. Than, it tries to insert new postnlOrder, and we get

```
Magento\Framework\Exception\CouldNotSaveException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tig_postnl_order`, CONSTRAINT `TIG_POSTNL_ORDER_QUOTE_ID_QUOTE_ENTITY_ID` FOREIGN KEY (`quote_id`) REFERENCES `quote` (`entity_id`) ON DELETE SET NULL), query was: 
INSERT INTO `tig_postnl_order` (`order_id`, `quote_id`, `type`, `delivery_date`, `product_code`, `parcel_count`, `ship_at`, `created_at`, `updated_at`) VALUES (?, ?, ?, ?, ?, ?, '2017-12-06', '2017-12-06 11:13:53', '2017-12-06 11:13:53') in vendor/tig/postnl-magento2/Model/OrderRepository.php:90Stack trace:
#0 vendor/tig/postnl-magento2/Observer/SalesOrderSaveAfter/CreatePostNLOrder.php(113): TIG\PostNL\Model\OrderRepository->save(Object(TIG\PostNL\Model\Order))
#1 vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): TIG\PostNL\Observer\SalesOrderSaveAfter\CreatePostNLOrder->execute(Object(Magento\Framework\Event\Observer))
#2 vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(TIG\PostNL\Observer\SalesOrderSaveAfter\CreatePostNLOrder), Object(Magento\Framework\Event\Observer))
#3 vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
```

Environment
--
PHP 7.0
Magento version 2.1.6
Extension version v1.2.0

**Comment by tig-jeffreybranderhorst** [comment]
Hi VesnaS,

Thank you for contacting us and you have a good point. Because of that I made a public issue so we can fix this. You can also keep on eye on the progress by clicking this link: https://jira.tig.nl/browse/POSTNLM2-416

We will fix this in the near future, thank you again for submitting this.
Sincerely,
Jeffrey Branderhorst.

**Comment by nesh-younify** [comment]
Another point, looking at observer code it's not clear to me why check is done using `quote_id` instead of `order_id`, Even if above error avoided it can still fail due to unique `order_id` index.

In addition observer should check that quote exist and set column to `NULL` if not due to FK constraint.

Let me know if I'm on the right track and if PR with patch/test patch for this is acceptable.

**Comment by tig-rikjonkmans** [comment]
Hi @nesh-younify,

Because of the Magento cron which removes the quotes, we have removed the FK constraint with the quote_id. We also added a new check which is using the order_id if the quote returns NULL. The reason we use the quote is because the PostNL order is created before the Magento Order. This is for the 'pakjegemak_address' and product options the customer is selecting during checkout. 

These fixes are in internal test situations and will be attached to the next release. Hope this has answered your questions. 

Sincerely, 
Rik Jonkmans

**Comment by nesh-younify** [comment]
Thanks for clarification.

Any chance that you can send me a patch (I understand that is not tested throughly)? Our current project is on hold due to this problem and we can use it as a band-aid solution till proper release comes out.

**Comment by tig-rikjonkmans** [comment]
Hi @nesh-younify,

To bad this fix is already integrated with a major version and is attached to upgrade scripts. To create a patch will mean, that we have to create a minor version, which i have to discuss with PostNL first. 

Sincerely,
Rik Jonkmans

**Comment by nesh-younify** [comment]
Thanks.

For now, I'll try to replicate fix you described so we can continue until proper version is released. 
Thanks for the help.

**Comment by tig-rikjonkmans** [comment]
Hi @nesh-younify and @VesnaS ,

The new release (v1.3.0) is out, thanks for your patience.
