### ISSUE TITLE
Shipping options visible while required qty isn't in stock

### ISSUE THREAD

**Issue by kaybeudeker** [tig-nl/postnl-magento2#45]
Despite [this commit](https://github.com/tig-nl/postnl-magento2/commit/4d5e71871019bedfb9792ec32ac46ed612307a33) we're still facing this issue.

### Preconditions
- magento/product-community-edition 2.2.2 (clean install + sample data, installed through composer)
- tig/postnl-magento2 v1.3.2 (installed through composer)

### Steps to reproduce
Settings PostNL extension:
- Enabled in **test modus**
- Activate shipping options: **Yes**
- Stock options: **Only for products that are in stock**
- Activate delivery days: **Yes**
- Activate post office locations: **Yes**

### Expected result
- Shipping options (delivery days and post office locations) shouldn't be visible, even if enabled, when the required qty isn't in stock.

### Actual result
- Shipping options are visible

### Note
- Console returns no errors and the PostNL logs are 'clean'

### Screenshot
![m222postnlv132-github](https://user-images.githubusercontent.com/31165120/37242441-dc521fda-2469-11e8-97f5-7ccaad286ed4.jpg)

**Comment by tig-dennisvanderhammen** [comment]
Hi Kaybeudeker,

Thank you for your issue. I've tried to reproduce this on my local environment and wasn't able to reproduce this here. What we usually see with this specific configuration is that it doesn't get saved properly. The cause is that the Stock options is editable without unchecking the 'Use system value' button.

Could you confirm for me if you unchecked this value when you chose for the "Only for products that are in stock" option? If this value is checked, it will still use the "Always show delivery options" value.
See screenshot below.
![screen shot 2018-03-12 at 15 57 48](https://user-images.githubusercontent.com/23072926/37291087-35b5b5a0-260e-11e8-9ac4-2f808a155b09.png)

**Comment by kaybeudeker** [comment]
Dennis,

Thanks for your quick reply.
I can confirm that in my first post i already had the "use system value" unchecked for all the settings under "steps to reproduce". To make sure i just reproduced/tested it again and noticed something strange(?):

### Unchecked "use system value" + DB records (settings like first post)
![postnl-shippingoptions-unchecked](https://user-images.githubusercontent.com/31165120/37336566-1904a606-26b2-11e8-954b-ef271247c75e.jpg)

### Checked "use system value" + DB records
![postnl-shippingoptions-checked](https://user-images.githubusercontent.com/31165120/37336570-1de22db0-26b2-11e8-8da1-1cf9dea2673a.jpg)

With "use system value" checked, it doesn't save the (default) value for the setting at all in the core_config_data table? 

Regarding the "stock options" with the "use system value" box checked, it doesn't make any diff saving it with "Always show..." or "Only for...", non is saved with "use system value" checked, only when unchecked.

Can you reproduce/confirm this?

Thanks in advance.

**Comment by tig-dennisvanderhammen** [comment]
Once I check the 'Use system value' I'm unable to find the in_stock value, I feel like this is intended behaviour because in this case we use the system value rather than the backend value.

We are using the path tig_postnl/shippingoptions/stockoptions for this, which appears to be correctly showing the value 'in_stock' in your case. Whenever I switch to "Always show.." the value seems to correctly switch to "backordered".

I also just set up a new environment and only installed the PostNL extension on this environment. I'm unable to reproduce your issue on this environment as well.

As I'm unable to reproduce this on a clean environment, I would like to continue this investigation by contacting you by e-mail. Could you send an e-mail to our servicedesk@tig.nl and include dennis.van.der.hammen@tig.nl in the CC?

**Comment by kaybeudeker** [comment]
Can you tell me more about your dev env (versions)? I would like to try to reproduce it on a similar env locally just to make sure..

**Comment by tig-dennisvanderhammen** [comment]
Of course
**Installing Magento, sampledata & PostNL** 
I installed Magento version 2.2.2 to match your Magento version, using 
`composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.2.2`
After installing 2.2.2 I installed the sample data using bin/magento. Then I installed our PostNL extension using composer require tig/postnl-magento2. 
I flushed & cleaned the cache, emptied generated/, var/cache/, var/page_cache/, var/view_processed/. I deployed the static content.

**Setting configs**
I changed the qty of a simple product to 1 and allowed 'backorder with notify customer'.
I put the PostNL extension in Test mode, inserted the shipping address, unchecked 'Use system value' for 'Activate shipping options' & 'Activate delivery days'. I kept everything else default.

Once I go to the frontend, select my product and change the quantity to 2 it notifies me that there's only one in stock. The result is no delivery options. When I change the quantity to 1 it does give me delivery options.

If you spot any differences with your environment, I'd be happy to hear that.

PS. I've tried this case on PHP 7.0.22 and PHP 7.0.27.

**Comment by kaybeudeker** [comment]
Interesting,

(Also, PHP 7.0.22)
When i reproduce it the way you describe it, it all works fine but that's not the way how we set the backorders.

We uncheck "**Use system value**" and select "**Allow qty Below 0 and Notify customer**" under **Configuration > Catalog > Inventory > Backorders** so it's set globally and we don't have to set backorders for each product, imo a normal approach for setting this up? 

Can you confirm this should work?

**Comment by tig-dennisvanderhammen** [comment]
Thank you for the clear explanation. I didn't take this option in consideration. You are right, this would be a normal approach for setting this up.

I've managed to reproduce your issue with this setup, therefore I created a backlog item for this issue: https://jira.tig.nl/browse/POSTNLM2-501.

**Comment by tig-dennisvanderhammen** [comment]
@kaybeudeker, we just released version v1.3.4 which contains a bug fix for the mentioned issue. You can find the other release notes for this update here: https://confluence.tig.nl/x/3YSC
