### ISSUE TITLE
v1.4.0 Array to string error

### ISSUE THREAD

**Issue by DeLuuk** [tig-nl/postnl-magento2#52]
Hey,

I have installed your PostNL extension on a webshop of mine but when I configured the test mode and tried to open the checkout page I got an error. The error says:

> Notice: Array to string conversion in /[host]/[user]/domains/[url]/public_html/vendor/magento/framework/DB/Pdo/Mysql.php on line 2999

I replaced all the secure bits with a [] and text.

Now I know this isn't a mistake in Magento 2 since the checkout works when the PostNL shipping method is turned off.

Hopefully you guys know something.

**Comment by tig-jaspersmits** [comment]
Hi DeLuuk,

Thank you for submitting this. The error you mention here seems to be a notice and not an error. This is a public library and is unrelated to the PostNL extension. My colleague took a look at the file which probably is located here?: 

`public/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php`

You seem to miss the "Adapter" part in the url.

He found this part in the Mysql.php file and it refers to 'longtext' being converted to a string. But we don't use 'longtext' in our PostNL extension. So we think something else is going wrong and because we can not reproduce this on our Magento 2.1 / 2.2 environments we suggest you send us an e-mail with Magento login information for a staging environment. You can send this to sd@tig.nl, we will then take a look at the problem.

Kind regards,

Jasper
TIG
