### ISSUE TITLE
observer CreatePostNLShipment getType from null

### ISSUE THREAD

**Issue by evs-xsarus** [tig-nl/postnl-magento2#75]
In function CreatePostNLShipment the order type is requested but $this->getOrder can result in null. If that happens, the following exception is thrown:

```
PHP Fatal error:  Uncaught Error: Call to a member function getType() on null in /home/mag/source/
vendor/tig/postnl-magento2/Observer/TIGPostNLShipmentSaveAfter/CreatePostNLShipment.php:202
Stack trace:
#0 /home/mag/source/mag.xsarus.net/vendor/tig/postnl-magento2/Observer/TIGPostNLShipmentSaveAfter/CreatePostNLShipment.php(164): TIG\\PostNL\\Observer\\TIGPostNLShipmentSaveAfter\\CreatePostNLShipment->getShipmentType()
#1 /home/mag/source/vendor/tig/postnl-magento2/Observer/TIGPostNLShipmentSaveAfter/CreatePostNLShipment.php(131): TIG\\PostNL\\Observer\\TIGPostNLShipmentSaveAfter\\CreatePostNLShipment->formatModelData(Object(Magento\\Sales\\Model\\Order\\Shipment))
#2 /home/mag/source/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): TIG\\PostNL\\Observer\\TIGPostNLShipmentSaveAfter\\CreatePostNLShipment->execute(Object(Magento\\Framework\\Event\\Observer))
#3 /home/mag/source/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): ...'
```

Could this be prevented? I'm using v1.5.0

**Comment by tig-timsibbald** [comment]
Hi @evs-xsarus ,
Thank you for submitting this. We will test this and get back to you to explain our findings and a possible solution.

Best regards,
Tim Sibbald

**Comment by tig-dennisvanderhammen** [comment]
@evs-xsarus,

There should be a record available in the tig_postnl_order table. One that links to the actual order you're trying to create a shipment of. There are a few 3rd extensions known where the PostNL order isn't properly created.

Do you happen to use the Multisafepay or Mollie extension, some kind of OneStepCheckout or maybe another payment provider that might cause issues?

**Comment by tig-jaspersmits** [comment]
Hereby I add the submission from @CsSatter like mentioned in: https://github.com/tig-nl/postnl-magento2/issues/76

When trying to ship orders through massAction for the following controllers:
TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsAndPrintPackingSlip
TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintPackingSlip
TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintShippingLabels

And an order is not a validPostNL order the following exception is thrown (anonymized file paths):
Fatal error: Uncaught Error: Call to a member function getShippingAddress() on null in /vendor/tig/postnl-magento2/Controller/Adminhtml/Order/CreateShipmentsConfirmAndPrintShippingLabels.php:138 Stack trace: #0 /vendor/tig/postnl-magento2/Controller/Adminhtml/Order/CreateShipmentsConfirmAndPrintShippingLabels.php(129): TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintShippingLabels->loadLabel(NULL) #1 /vendor/tig/postnl-magento2/Controller/Adminhtml/Order/CreateShipmentsConfirmAndPrintShippingLabels.php(105): TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintShippingLabels->createShipmentsAndLoadLabels() #2 /vendor/magento/framework/App/Action/Action.php(107): TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintShippingLabels->execute() #3 /vendor/tig/postnl-magento2/Controller/Adminhtml/Order/CreateShipmentsConfirmAndPrintShippingLabels.php on line 138

This is due to execute method in the controller:
$shipment = $this->createShipment->create($shipment); $this->loadLabels($shipment);

This is because $shipment in this case has a null value passed to the loadLabels method to getShippingAddress(), in TIG\PostNL\Service\Shipment\CreateShipment the create method returns null when the isValidOrder() method returns false. isValidOrder() in this case returns false due to TIG\PostNL\Helper\Data:isPostNLOrder().
Understandably this method will return true if the shipping method specified for the order has been configured for PostNL shipments as well.

However due to user error being a thing an unsuspecting user can (accidently) come across this exception.

Steps to reproduce error:

Create order as customer, use a shipping method not configured for PostNL shipments
Try to ship the created order through PostNL

**Comment by evs-xsarus** [comment]
My installation uses the following packages:

```json
        "magento/product-community-edition": "2.2.5",
        "php-amqplib/php-amqplib": "^2.6",
        "ebizmarts/magento2-magemonkey": "^3.0",
        "ebizmarts/magento2-mandrill": "^3.0",
        "ebizmarts/magento2-abandonedcart": "^3.0",
        "ebizmarts/magento2-autoresponder": "^3.0",
        "tig/buckaroo": "^1.3",
        "tig/postnl-magento2": "^1.1",
        "afterpay/afterpay-module": "^1.4",
        "magepal/magento2-gmailsmtpapp": "^1.4",
        "honl/magento2-nl-nl": "^1.1",
        "magmodules/magento2-channable": "^1.0",
        "amasty/shopby": "^2.5",
```
I've checked table `tig_postnl_order` and it holds ~675 records where order_id is null.

**Comment by tig-jaspersmits** [comment]
Hi @evs-xsarus,

Is it possible to test without Afterpay activated in your environment? This is most likely caused by a 3rd party PSP extension. 

Looking forward to your response.

Kind regards,

Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi @evs-xsarus,

Version 1.6.0 just got released. Could you try the new version and see if the problem is solved? Looking forward to your response.

Kind regards,

Jasper
TIG

**Comment by evs-xsarus** [comment]
I'm in the process of testing this version and expect to have results around 7 december.

**Comment by tig-jaspersmits** [comment]
Hi @evs-xsarus,

Did this solve the problem for you?

Kind regards,

Jasper
TIG

**Comment by evs-xsarus** [comment]
Hi, 

It seems to be fixed now. Tnx.
