### ISSUE TITLE
Not possible to save module settings

### ISSUE THREAD

**Issue by kaybeudeker** [tig-nl/postnl-magento2#83]
- [X] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [X] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

--- 

### Bug:
- With version 1.6.0 of the module you can't seem to save to backend settings of the module. The orange 'save settings' button isn't saving + reloading the page but acts like a "scroll back to top" button when you'r scrolled down, and doesn't react at all when not scrolled down. Issue persists with Chrome, Firefox and Safari. Mag 2.2.7.

Merry X-mas ;)

**Comment by tig-dennisvanderhammen** [comment]
Hi @kaybeudeker,

Thank you for your submission. You as well, a merry Christmas!

As for your issue, could you please open the "General configuration and account information / Senders address" tab for me ("Algemene configuratie en account informatie / Adres van afzender" in Dutch)? 

Either the name, or a company name is mandatory for the PostNL extension to work. Not filling either of these in provides a 500 error when trying to create a label. To prevent this, we made both of these mandatory, instead of having none being mandatory.

Unfortunately, when a validation error occurs, Magento doesn't open the tab where the validation error occurs, which might cause some confusion when trying to save settings without these filled in.

**Comment by kaybeudeker** [comment]
We didn't had the first- and last name fields filled in, that fixed it.
We had no issues with saving the module settings before version 1.6.0 (never filled in those fields actually), nor we had errors trying to create labels (even now with v1.6.0)?
What if i don't want the first- and lastname on the label?

**Comment by tig-daanvandenbergh** [comment]
As we haven't received a response in a while, I'm closing this issue.
